---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
  cachier: machine
  parallel: true
platforms:
  - name: linux
    box: jtarpley/${MOLECULE_BOX:-rocky9_cis}
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: duo_authentication_proxy_
    groups:
      - subjects
  - name: dc
    box: jtarpley/${MOLECULE_WIN_BOX:-w2022_cis}
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: duo_authentication_proxy_
    groups:
      - windows
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ad_domain_fqdn: test.local
        ad_domain_base_dn: DC=test,DC=local
      subjects:
        duoap_api_host: api-26a75eeb.duosecurity.com
        duoap_temp_path: /home/vagrant/duoap
        duoap_cert_path: >-
          {{ '/etc/pki/ca-trust/source/anchors' if ansible_os_family == 'RedHat' else '/usr/share/ca-certificates' }}
        duoap_ad_clients:
          - comment: "Active Directory {{ ad_domain_fqdn }}"
            hosts:
              - "dc.{{ ad_domain_fqdn }}"
            transport: ldaps
            search_dn: "{{ ad_domain_base_dn }}"
            ssl_ca_certs_file: "{{ duoap_cert_path }}/winca.pem"
            port: 636
        duoap_dirsync_clouds:
          - comment: Directory Sync
            ikey: DIXXXXXXXXXXXXXXXXXX
            skey: deadbeefdeadbeefdeadbeefdeadbeefdeadbeef
        duoap_service_account_username: "vagrant@{{ ad_domain_fqdn }}"
        duoap_service_account_password: vagrant
        duoap_upgrade: ${MOLECULE_DUO_UPGRADE:-false}
        duoap_cleanup_old_versions: ${MOLECULE_DUO_UPGRADE:-false}
      windows:
        ansible_shell_type: powershell
        ansible_become_method: runas
        ansible_become_user: SYSTEM
        ansible_password: vagrant
    host_vars:
      dc:
        ansible_ssh_common_args: >-
          -o PreferredAuthentications=password
          -o PubkeyAuthentication=no
          -o UserKnownHostsFile=/dev/null
          -o ControlMaster=auto
          -o ControlPersist=60s
          -o ForwardX11=no
          -o LogLevel=ERROR
          -o StrictHostKeyChecking=no
verifier:
  name: ansible
