---
- name: Prepare DC
  hosts:
    - dc
  pre_tasks:
    - name: Copy files to DC
      loop:
        - dc.pfx
        - winca.pem
      ansible.windows.win_copy:
        src: "files/{{ item }}"
        dest: C:\Windows\temp\

    - name: Import certificate
      loop:
        - file_type: pem
          path: winca.pem
          store_name: Root
        - file_type: pkcs12
          key_storage: machine
          password: SecurePassword1234!
          path: dc.pfx
          store_name: My
      ansible.windows.win_certificate_store:
        file_type: "{{ item.file_type }}"
        key_storage: "{{ item.key_storage | default(omit) }}"
        password: "{{ item.password | default(omit) }}"
        path: "C:\\Windows\\temp\\{{ item.path }}"
        store_location: LocalMachine
        store_name: "{{ item.store_name }}"
        store_type: system
        state: present
      loop_control:
        label: "{{ item.path }}"
  roles:
    - role: trippsc2.ad.testing_domain_controller

- name: Prepare Linux
  hosts:
    - linux
  become: true
  pre_tasks:
    - name: Add DC to hosts file
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ hostvars['dc'].ansible_host }} dc.{{ ad_domain_fqdn }} dc"
        owner: root
        group: root
        mode: '0644'

    - name: Copy CA file to host
      when:
        - ansible_os_family == 'RedHat'
      ansible.builtin.copy:
        src: files/winca.pem
        dest: /etc/pki/ca-trust/source/anchors/
        owner: root
        group: root
        mode: '0644'
      notify:
        - _update_ca_trust

    - name: Copy CA file to host
      when:
        - ansible_os_family == 'Debian'
      ansible.builtin.copy:
        src: files/winca.pem
        dest: /usr/share/ca-certificates/
        owner: root
        group: root
        mode: '0644'
      notify:
        - _update_ca_certificates

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Pre-install DUO Authentication Proxy
      when:
        - duoap_upgrade
      ansible.builtin.include_role:
        name: trippsc2.duo.authentication_proxy
      vars:
        duoap_version: '6.2.0'
  handlers:
    - name: Update CA trust
      listen: _update_ca_trust
      ansible.builtin.command: |
        update-ca-trust
      changed_when: true

    - name: Update CA certificates
      listen: _update_ca_certificates
      ansible.builtin.command: |
        update-ca-certificates
      changed_when: true
