---
name: Generate Role Docs
'on':
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - galaxy.yml
      - roles/authentication_proxy/.aar_doc.yml
      - roles/authentication_proxy/README.md
      - roles/authentication_proxy/meta/argument_specs.yml
      - roles/authentication_proxy/meta/main.yml
defaults:
  run:
    working-directory: 'trippsc2.duo'
jobs:
  docs_authentication_proxy:
    name: Generate authentication_proxy role documentation
    permissions:
      contents: write
    runs-on:
      - self-hosted
      - linux
      - ansible
      - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: trippsc2.duo
          ref: main
      - name: Generate authentication_proxy role documentation
        working-directory: 'trippsc2.duo'
        run: |
          source ~/venv/ansible-2.16/bin/activate
          cd ./roles/authentication_proxy
          aar-doc . markdown
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add README.md || /bin/true
          git commit -m "Update authentication_proxy role documentation." || /bin/true
          git push origin main
          deactivate
